spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.178.254.171:3306/testMp?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    secondary:
      initial-size: 5
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
      validation-query: SELECT 1

#禁止自启动
  batch:
    job:
      enabled: false
server:
  port: 8080
  address: 0.0.0.0




